### ISSUE TITLE
Create new branch and add user. Protect branches

### ISSUE THREAD

**Issue by asmirnov253** [Practical-DevOps-GitHub/devops-github-task-asmirnov253#1]
# Task on GitHub Topic

1. Add user `softservedata` to this repository.

2. Create branch `develop` as default branch.

3. Protect branches `main` and `develop` with these rules:
- user can't merge to both branches without pull request
- allowed to merge to `develop` branch only if we have 2 approvals
- merge to `main` branch allowed if only owner approved PR
- assign the user `softservedata` as the code owner for all the files in the `main` branch
4. Add template (pull_request_template.md) to `.github` directory for creating issue in format:

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update

5. Create project for this repository.

6. Add deploy key with name `DEPLOY_KEY` to your repository.

7. Create discord server and add notification when PR was created.

8. For github actions: 
- create PAT (Personal Access Token) with **Full control of private repositories** and **Full control of orgs and teams, read and write org projects**
- add to repository actions secrets key with the name `PAT` and the value of the created PAT

**Comment by asmirnov253** [comment]
Task was completed and tests passed successfully
https://github.com/Practical-DevOps-GitHub/devops-github-task-asmirnov253/actions/runs/7433631522
